openapi: 3.0.1
info:
  title: monster-giant-owl
  x-cortex-tag: monster-giant-owl
  x-cortex-custom-metadata:
    alignment: neutral
    type: dragon
    challenge_rating: 22
    legendary: false
    armor_class: 20
    hit_points: 37
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-giant-owl
      alias: github-token-test
